using Business.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Business.Interfaces
{

    /*
     
     This part is generated by Chat GPT 4o. I Was mosly unsure about the types and what to use for IEnumerable-part
     as well as "User?" for the method "FindUserByID", therefor asking Chat GPT 4o.
     So the interface is like a blueprint that tells all classes that uses this interface, must have these methods. 
     So kind of like an "agreement, between interface and classes using the interface"

     So the  IEnumerable<User> GetAllUsers() Gives us a simple way of interating through a collection of objects.
     Without actually having to know how many objects it contains or how it is structured and so on. 

     The User? FindUserById simply returns a User-object or null(?) if no user is found. 

     */
    public interface IUserService
    {
        void AddUser(User user); 

        List<User> GetAllUsers();
    }
}
